name: GUI
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.1.19=haa95532_0
  - certifi=2020.12.5=py38haa95532_0
  - intel-openmp=2020.2=254
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38h196d8e1_0
  - mkl_fft=1.2.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - numpy=1.19.2=py38hadc3359_0
  - numpy-base=1.19.2=py38ha3acd2a_0
  - openssl=1.1.1i=h2bbff1b_0
  - pandas=1.2.1=py38hf11a4ad_0
  - pip=20.3.3=py38haa95532_0
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - setuptools=52.0.0=py38haa95532_0
  - six=1.15.0=py38haa95532_0
  - sqlite=3.33.0=h2a8f88b_0
  - tk=8.6.10=he774522_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
  - zlib=1.2.11=h62dcd97_4
prefix: C:\Users\erikh\anaconda3\envs\GUI
